### ISSUE TITLE
当一个record所有字段的值都是None时会触发异常

### ISSUE THREAD

**Issue by wiiiky** [aliyun/aliyun-datahub-sdk-python#10]
异常为**ValueError: max() arg is an empty sequence**

https://github.com/aliyun/aliyun-datahub-sdk-python/blob/a23ce739be6b4b9b8135233cfa5fe5ec324cf055/datahub/models/record.py#L362

**Comment by wiiiky** [comment]
不过这个错误应该只会在交互的情况下触发。

**Comment by noosc** [comment]
fixed
