### ISSUE TITLE
building 'cprotobuf.internal' extension

### ISSUE THREAD

**Issue by liuguangrui123** [aliyun/aliyun-datahub-sdk-python#28]
copying cprotobuf\plugin_pb.py -> build\lib.win-amd64-3.5\cprotobuf
    copying cprotobuf\__init__.py -> build\lib.win-amd64-3.5\cprotobuf
    running build_ext
    building 'cprotobuf.internal' extension
    error: [WinError 2] 系统找不到指定的文件

**Comment by liuguangrui123** [comment]
window10系统 安装pipi nstall datahub 出现这个错误

**Comment by lvgitt** [comment]
同样问题，不知道楼主解决没

**Comment by noosc** [comment]
> 同样问题，不知道楼主解决没

https://help.aliyun.com/document_detail/50364.html?spm=a2c4g.11186623.6.557.2db46b07IHDBnO#
参照一下，常见问题

**Comment by lvgitt** [comment]
Microsoft Visual C++ 14.0 standalone: Visual C++ Build Tools 2015 (x86, x64, ARM) 这个没地方下载

**Comment by noosc** [comment]
> Microsoft Visual C++ 14.0 standalone: Visual C++ Build Tools 2015 (x86, x64, ARM) 这个没地方下载

https://visualstudio.microsoft.com/zh-hans/downloads/
现在微软的页面里都统一掉了，就下”Visual Studio 2019 生成工具“，是一个下载器，里面再挑自己对应的版本来装

**Comment by lvgitt** [comment]
![image](https://user-images.githubusercontent.com/44693144/66559995-0c3ecd00-eb89-11e9-9c34-17c72912732c.png)
下载哪个呢？

**Comment by noosc** [comment]
> ![image](https://user-images.githubusercontent.com/44693144/66559995-0c3ecd00-eb89-11e9-9c34-17c72912732c.png)
> 下载哪个呢？

2015 不是只有1个么

**Comment by lvgitt** [comment]
安装完
![image](https://user-images.githubusercontent.com/44693144/66561852-e1ef0e80-eb8c-11e9-8b02-f5a53f59ea82.png)
后执行 ' pip install pydatahub'
提示：
`    internal.c
    c1: fatal error C1083: 无法打开源文件: “cprotobuf/internal.c”: No such file or directory
    error: command 'D:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\B
IN\\x86_amd64\\cl.exe' failed with exit status 2`

**Comment by noosc** [comment]
有没有检查过 setuptools 版本是否满足要求

**Comment by lvgitt** [comment]
![image](https://user-images.githubusercontent.com/44693144/66616465-71370900-ec03-11e9-9992-83b2f3a48df0.png)
所有版本都满足要求，除了 cprotobuf 安装时报错
![image](https://user-images.githubusercontent.com/44693144/66616513-a6435b80-ec03-11e9-8f47-dabfac089ab7.png)

**Comment by noosc** [comment]
看下是不是装的 cprotobuf==0.1.10，这个是作者新发的版本，看着必须要安装cython才能用，不然就手动自己pip install cprotobuf==0.1.9

**Comment by lvgitt** [comment]
执行
`pip install cython`后，
再执行
`pip install cprotobuf==0.1.9`
报如下错误
`    internal.c
    d:\program files\dev\python\include\pyconfig.h(203): fatal error C1083: 无法
打开包括文件: “basetsd.h”: No such file or directory
    error: command 'D:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\B
IN\\x86_amd64\\cl.exe' failed with exit status 2`

**Comment by noosc** [comment]
https://stackoverflow.com/questions/23691564/running-cython-in-windows-x64-fatal-error-c1083-cannot-open-include-file-ba/42624713#42624713

**Comment by lvgitt** [comment]
装个这东西这么麻烦，我还是去研究java的sdk吧

**Comment by noosc** [comment]
python sdk 依赖 cprotobuf做pb序列化反序列化，现在指定了依赖版本为0.1.9，在安装时可以依赖cython，也可以自己编译extension。windows编译环境的准备工作相对复杂，但过程中的报错基本都能google到解决方法。[官方文档](https://help.aliyun.com/document_detail/158848.html?spm=a2c4g.11186623.6.592.2e134c079GiPdX#h2-u5E38u89C1u95EEu98983)也列了一些常见的错误
