### ISSUE TITLE
get_tuple_records 不能获取字段是null

### ISSUE THREAD

**Issue by sultra** [aliyun/aliyun-datahub-sdk-python#32]
DatahubException   异常
**"The values set to records are against the schema, expect len 8, got len 7"**  错误

debug  发现是直接使用  datahub.DataHub.get_tuple_records 这个方法时就出现该问题
数据中是有字段是null值，不是"null"；很明显SDK并不能获取到null数据，但实际datahub端允许有null！
期待有解决方法！

**Comment by noosc** [comment]
> DatahubException 异常
> **"The values set to records are against the schema, expect len 8, got len 7"** 错误
> 
> debug 发现是直接使用 datahub.DataHub.get_tuple_records 这个方法时就出现该问题
> 数据中是有字段是null值，不是"null"；很明显SDK并不能获取到null数据，但实际datahub端允许有null！
> 期待有解决方法！

这个问题是这样的，get_tuple_records 参数中指定的schema有8列，但是读到的数据是7列，应该是topic有新增过列导致的。现在的校验过于严格，行为已经修正，发布了2.17.0版本。

有其他问题可以在（钉钉群：33517130 ）快速沟通。
