### ISSUE TITLE
AttributeError: 'DataHub' object has no attribute 'list_shards'

### ISSUE THREAD

**Issue by wiiiky** [aliyun/aliyun-datahub-sdk-python#8]
我看README里写的方法是**list_shards**，但代码里对应的方法名却是**list_shard**。有个地方写错了吧。

https://github.com/aliyun/aliyun-datahub-sdk-python/blob/d3b57f067b9b9d328578b10607c1da235cab9f2d/datahub/core.py#L226

**Comment by noosc** [comment]
@wiiiky 谢谢，已更正
